VER = 0.1.5

TMP ?= /tmp
PREFIX ?= /usr
SHAREDIR ?= $(PREFIX)/share
MANDIR ?= $(SHAREDIR)/man
DOCDIR ?= $(SHAREDIR)/doc
BINDIR ?= $(PREFIX)/bin
SBINDIR ?= $(PREFIX)/sbin
PKGDIR = $(TMP)/yalpack-$(VER)
PKGDEST = $(PKGDIR)/dest

all:
	@echo
	@echo To install to the system, and then reinstall as a package \(recommended for first-time installations\), run \'make package\'.
	@echo
	@echo For upgrades, use \'DESTDIR=$(PKGDEST) make install\' and make a NAME file. Then, use pkgmake and pkgup as usual.
	@echo
	@echo \'make clean\' will remove compressed man pages from this directory and delete LICENSE and README from src/doc.
	@echo
	@echo \'make uninstall\' will uninstall yalpack from the specified DESTDIR. Please note that /var/yalpack and its subdirectories are generated by running yalpack scripts, and must be removed manually if desired.
	@echo

install:
	@echo
	@rm -rf man-gz
	@mkdir -pv $(DESTDIR)$(BINDIR)
	@mkdir -pv $(DESTDIR)$(SBINDIR)
	@mkdir -pv man-gz
	@mkdir -pv $(DESTDIR)$(SHAREDIR)/yalpack
	@mkdir -pv $(DESTDIR)$(MANDIR)/man1
	@mkdir -pv $(DESTDIR)$(MANDIR)/man5
	@mkdir -pv $(DESTDIR)$(DOCDIR)/yalpack-$(VER)
	@cp -v --preserve=mode,timestamps ./{LICENSE,README,Customization,man-pages} src/doc/
	@cp -v --preserve=mode,timestamps src/doc/* $(DESTDIR)$(DOCDIR)/yalpack-$(VER)/
	@cp -v --preserve=mode,timestamps src/bin/* $(DESTDIR)$(BINDIR)/
	@cp -v --preserve=mode,timestamps src/sbin/* $(DESTDIR)$(SBINDIR)/
	@cp -v --preserve=mode,timestamps src/share/* $(DESTDIR)$(SHAREDIR)/yalpack/
	@cp -v --preserve=mode,timestamps src/man/* man-gz/
	@gzip man-gz/*
	@cp -v --preserve=mode,timestamps man-gz/*1* $(DESTDIR)$(MANDIR)/man1/
	@cp -v --preserve=mode,timestamps man-gz/*5* $(DESTDIR)$(MANDIR)/man5/
	@chmod 744 $(DESTDIR)$(SBINDIR)/{pkgcheck,pkginst,pkgmake,pkgremove,pkgup,liblist}
	@chmod 755 $(DESTDIR)$(BINDIR)/{libcheck,libprecise,pkglist,pkgfind}
	@chmod 744 $(DESTDIR)$(SHAREDIR)/yalpack/*
	@echo
	@echo Files moved to $(DESTDIR)
	@echo
	@echo Running the install script now.
	@chmod 755 src/install.sh
	@./src/install.sh
	@echo If an existing yalpack installation is to be upgraded, make a NAME file under $(PKGDIR) before running pkgmake and pkgup.
	@echo

package:
	@echo
	@rm -rf man-gz
	@mkdir -pv $(DESTDIR)$(BINDIR)
	@mkdir -pv $(DESTDIR)$(SBINDIR)
	@cp -v --preserve=mode,timestamps src/bin/* $(DESTDIR)$(BINDIR)/
	@cp -v --preserve=mode,timestamps src/sbin/* $(DESTDIR)$(SBINDIR)/
	@chmod 744 $(DESTDIR)$(SBINDIR)/{pkgcheck,pkginst,pkgmake,pkgremove,pkgup,liblist}
	@chmod 755 $(DESTDIR)$(BINDIR)/{libcheck,libprecise,pkglist,pkgfind}
	@rm -rvf $(PKGDEST)
	@mkdir -pv $(PKGDEST)
	@mkdir -pv $(PKGDEST)$(BINDIR)
	@mkdir -pv $(PKGDEST)$(SBINDIR)
	@mkdir -pv $(PKGDEST)$(SHAREDIR)/yalpack
	@mkdir -pv $(PKGDEST)$(MANDIR)/man1
	@mkdir -pv $(PKGDEST)$(MANDIR)/man5
	@mkdir -pv $(PKGDEST)$(DOCDIR)/yalpack-$(VER)
	@mkdir -pv man-gz
	@cp -v --preserve=mode,timestamps ./{LICENSE,README,Customization,man-pages} src/doc/
	@cp -v --preserve=mode,timestamps src/doc/* $(PKGDEST)$(DOCDIR)/yalpack-$(VER)/
	@cp -v --preserve=mode,timestamps src/bin/* $(PKGDEST)$(BINDIR)/
	@cp -v --preserve=mode,timestamps src/sbin/* $(PKGDEST)$(SBINDIR)/
	@cp -v --preserve=mode,timestamps src/share/* $(PKGDEST)$(SHAREDIR)/yalpack/
	@cp -v --preserve=mode,timestamps src/man/* man-gz/
	@gzip man-gz/*
	@cp -v --preserve=mode,timestamps man-gz/*1* $(PKGDEST)$(MANDIR)/man1
	@cp -v --preserve=mode,timestamps man-gz/*5* $(PKGDEST)$(MANDIR)/man5
	@chmod 744 $(PKGDEST)$(SBINDIR)/{pkgcheck,pkginst,pkgmake,pkgremove,pkgup,liblist}
	@chmod 755 $(PKGDEST)$(BINDIR)/{libcheck,libprecise,pkglist,pkgfind}
	@chmod 744 $(PKGDEST)$(SHAREDIR)/yalpack/*
	@cp -v --preserve=mode,timestamps src/install.sh $(PKGDIR)
	@chmod 755 $(PKGDIR)/install.sh
	@echo yalpack > $(PKGDIR)/NAME
	@pkgmake yalpack-$(VER)
	@pkginst yalpack-$(VER)
	@echo '	'$(tput smul)yalpack$(tput rmul) should now be installed as a package. Run $(tput smul)pkglist$(tput rmul) to confirm.
	@echo

clean:
	@echo
	@rm -rvf man-gz
	@rm -vf src/doc/{LICENSE,README,Customization,man-pages}
	@echo
	
uninstall:
	@echo
	@rm -vf $(DESTDIR)$(SBINDIR)/{pkgcheck,pkginst,pkgmake,pkgremove,pkgup,liblist}
	@rm -vf $(DESTDIR)$(BINDIR)/{libcheck,libprecise,pkglist,pkgfind}
	@rm -vf $(DESTDIR)$(MANDIR)/man1/{pkgcheck,pkgfind,pkginst,pkglist,pkgmake,pkgremove,pkgup,liblist,libcheck,libprecise}.1*
	@rm -vf $(DESTDIR)$(MANDIR)/man5/{restore-yalpack,newfile-yalpack}.5*
	@rm -rvf $(DESTDIR)$(SHAREDIR)/yalpack
	@rm -rvf $(DESTDIR)$(DOCDIR)/yalpack-$(VER)
	@echo
	@echo Complete. The yalpack directory in /var \(which includes package and library information\) can be removed by administrator discretion if it exists.
