.\" Manpage for libcheck
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "22 June 2021" "0.1.5" "libcheck man page"
.SH NAME
libcheck \- generate information about which binaries use dynamic libraries conforming to a search term
.SH SYNOPSIS
libcheck LIBRARY
.SH DESCRIPTION
libcheck is a shell program provided by yalpack (Yet Another Lfs PACKage manager) for collecting information which binaries use dynamic libraries conforming to a search term. Information on individual binaries is based on the most recent run of liblist(1), so the binaries are those in the following locations (unless /usr/sbin/liblist was edited):

\t /bin
\t /usr/*
\t /opt/*
\t /sbin

libcheck will not produce duplicate results on systems where one or more of these locations is a symlink.

In addition, a list of dynamic libraries conforming to the original search term is provided; for more exact results, libprecise(1) can be used on a specific library prefix.
.SH OPTIONS
LIBRARY - A search term for the desired library.

-h|--help - Display the help menu.
.SH SEE ALSO
pkgcheck(1), liblist(1), libprecise(1)
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
