.\" Manpage for libprecise
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "21 May 2021" "0.1.3" "libcheck man page"
.SH NAME
libprecise \- generate information about which binaries use a particular library
.SH SYNOPSIS
libcheck LIBRARY
.SH DESCRIPTION
libcheck is a shell program provided by yalpack (Yet Anotehr Lfs PACKage manager) for collecting information which binaries use a particular dynamic library existing in the form "LIBRARY.*". Information on individual binaries is based on the most recent run of liblist(1), so the binaries are those in the following locations (unless /sbin/liblist was edited):

\t /bin
\t /usr/*
\t /opt/*
\t /sbin
.SH OPTIONS
LIBRARY - A search term for the desired library; the library suffix is not needed.

-h|--help - Display the help menu.
.SH SEE ALSO
pkgcheck(1), liblist(1), libcheck(1)
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
