.\" Manpage for /usr/share/yalpack/newfiles
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 8 "27 August 2021" "0.2.0" "newfiles man page"
.SH NAME
newfiles \- update and optionally manage .new files belonging to yalpack-installed packages
.SH SYNOPSIS
/usr/share/yalpack/newfiles (default location)
.SH DESCRIPTION
newfiles is a shell program provided by yalpack (Yet Another Lfs PACKage manager) for updating the .new files lists in /var/yalpack/pkgdata/NEWFILES. Files are listed here under the following conditions:

\t The file exists on the system at the time .new files are evaluated

\t The file ends in ".new"

\t The file is provided by a yalpack-installed package

Running the script will update all lists in NEWFILES to reflect the files installed on the system at the time of running. The NEWFILES directory is also updated by pkginst(1), pkgup(1) and pkgremove(1) on an individual-package basis.

newfiles allows the administrator to take the opportunity to manage .new files on the system; the following options are available for each discovered .new file:

\t o - Overwrite the original file with the .new file.

\t b - Back up the original file at (filename).old, and then overwrite using the .new file.

\t r - Remove the .new file.

\t k - Keep both files as they are for the time being.

\t d - Use diff on the two files. If /usr/bin/less is installed on the system, it will be used to display the results. Return to the option menu afterwards.

\t x - Exit the newfiles script

In all cases, overwrites will preserve the ownership and mode of the .new file. These will be the same as the ownership and mode of the original file at the time of installation, provided that they have not been changed in the meantime. See pkginst(1) for details. newfiles follows symlinks when performing copy operations, and has been tested on merged-usr systems.

If the non-.new file no longer exists on the system at the time newfiles is run, newfiles will offer to move the .new file into the correct location in lieu of displaying the options above. This should only happen if the original file was on the system at the time of installation or upgrade, and has since been moved or deleted.

If the yalpack data directory is missing or damaged, running restore-yalpack(8) can update the contents of NEWFILES (provided that a good package tree backup is available; see restore-yalpack(8) for details). Because restore-yalpack(8) takes longer to run than newfiles and has no management helper, it is generally better to use newfiles if possible.
.SH SEE ALSO
pkginst(1), pkgup(1), pkgremove(1), restore-yalpack(8)
.SH BUGS
None known.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
