.\" Manpage for pkglist
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "5 May 2021" "0.1.1" "pkglist man page"
.SH NAME
pkglist \- return a list of installed yalpack packages
.SH SYNOPSIS
pkglist [-n|--new] [NAME]
.SH DESCRIPTION
pkglist is a shell program provided by yalpack (Yet Anotehr Lfs PACKage manager) for listing installed packages. pkglist references the following directories:

\t /var/yalpack/TREES

\t /var/yalpack/VER

Calling pkglist with a search term is supported, providing an easy way to get the version number for a package.
.SH OPTIONS
-n|--name - Return a list with package names only (no version).

NAME - pkglist will return only those packages matching NAME as a search term.
.SH SEE ALSO
pkginst(1), pkgup(1)
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
