.\" Manpage for pkglist
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "3 May 2021" "0.1.0" "pkglist man page"
.SH NAME
pkglist \- return a list of installed yalpack packages
.SH SYNOPSIS
pkglist [NAME]
.SH DESCRIPTION
pkglist is a shell program provided by yalpack (Yet Anotehr Lfs PACKage manager) for listing installed packages. pkglist references the following directories:

\t /var/yalpack/TREES

\t /var/yalpack/VER

Calling pkglist with a search term is supported, providing an easy way to get the version number for a package.
.SH SEE ALSO
pkginst(1), pkgup(1)
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
