.\" Manpage for pkgremove
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "5 May 2021" "0.1.1" "pkgremove man page"
.SH NAME
pkgremove \- remove a pkgmake-made and pkginst-installed package from LFS
.SH SYNOPSIS
pkgremove NAME
.SH DESCRIPTION
pkgremove is a shell program provided by yalpack (Yet Another Lfs PACKage manager) to remove packages made by pkgmake and installed by pkginst. The tarball for the package must be present.

pkgremove references /var/yalpack/pkgdata/TREES to remove any unneeded files, symlinks or directories installed by the package. Because the home directory is the responsibility of the user/administrator, pkgremove will never remove anything from /home. All files and directories related to the removed package will be deleted from /var/yalpack/pkgdata.

In case of library changes, ldconfig will be invoked.

By default, pkgup references the following directory:

\t /var/yalpack/pkgdata/TREES

The following data files and directories will be removed:

\t /var/yalpack/pkgdata/TREES/[NAME] (a file with the package directory tree)

\t /var/yalpack/pkgdata/VER/[NAME] (a file with the package's version number)

\t /var/yalpack/pkgdata/PKG-DEPS/[NAME]/libdeps (any libraries used by installed binaries)

\t /var/yalpack/pkgdata/PKG-BINS/[NAME]/instbins (any installed programs)

\t /var/yalpack/pkgdata/PKG-LIBS/[NAME]/libs (any installed libraries)

The pkgremove script can be edited to change any of these default locations to suit user preferences. This is best done prior to installation and in conjunction with the other yalpack scripts.
.SH OPTIONS
NAME - the name of the package to be removed. "pkglist -n" can be checked with a search term to verify exact package names. 
.SH SEE ALSO
pkgmake(1), pkginst(1), pkgcheck(1), pkgup(1)
.SH BUGS
None known
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
