.\" Manpage for pkgup
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "07 June 2021" "0.1.4" "pkgup man page"
.SH NAME
pkgup \- upgrade a pkgmake-made and pkginst-installed package in LFS
.SH SYNOPSIS
pkgup [-ykr|--yes --keep --root-own] OLDNAME NEWNAME-NEWVERSION
.SH DESCRIPTION
pkgup is a shell program provided by yalpack (Yet Another Lfs PACKage manager) to upgrade packages made by pkgmake and installed by pkginst. The TREE and VER (if applicable) files for the old version must be present, along with a package tarball for the new version.

pkgup begins by installing the new package with pkginst(1); from here, /var/yalpack/pkgdata/TREES is referenced to remove any unneeded files, symlinks or directories installed by the old version of the package. Because the home directory is the responsibility of the user/administrator, pkgup will never remove anything from /home.

By default, pkgup references and writes to the following directories:

\t /var/yalpack/pkgdata/TREES/[NAME] (a copy of the package tree is written here for reference)

\t /var/yalpack/pkgdata/VER/[NAME] (a file with the package's version number)

\t /var/yalpack/pkgdata/PKG-DEPS/[NAME]/libdeps (any libraries used by installed binaries)

\t /var/yalpack/pkgdata/PKG-BINS/[NAME]/instbins (any installed programs)

\t /var/yalpack/pkgdata/PKG-LIBS/[NAME]/libs (any installed libraries)

The pkgup script can be edited to change any of these default locations to suit user preferences. This is best done before installation and in conjunction with the other yalpack scripts.

The first "NAME" field must include the name of the outgoing package in its entirety, e.g.

\t pkgup yalpack yalpack-0.1.4 # If upgrading yalpack-* to yalpack-0.1.4

In cases where versioning information is included in the name,

\t pkgup kernel-5.12.0 kernel-5.12.1

would be appropriate. Check "pkglist -n" with a search term to find the exact package name.
.SH GLIBC AND INIT
If /sbin/init or glibc has been upgraded, init may need to reload in order to reboot or halt safely. If such an upgrade is detected, 

\t /sbin/telinit U 

is used to reload init before the pkgup upgrade process concludes.
.SH OPTIONS
OLDNAME - The name of the outgoing package.

NEWNAME - The name of the incoming package (in most cases, this will be the same).

NEWVERSION - The incoming package's version number. Not needed if NEWNAME contains versioning information and matches the name of the package tarball.

-k|--keep - Retain the incoming package tarball after installation.

-y|--yes - Disable the manual confirmation dialog.

-r|--root-own - Change the ownership of the incoming package contents to root:root. Useful if the package contents were built and are owned by an unprivileged user.

-h|--help - Display the help menu.
.SH SEE ALSO
pkgmake(1), pkginst(1), pkgcheck(1), pkgremove(1)
.SH BUGS
None known.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
