.\" Manpage for pkgup
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "3 May 2021" "0.1.0" "pkgup man page"
.SH NAME
pkgup \- upgrade a pkgmake-made and pkginst-installed package in LFS
.SH SYNOPSIS
pkgup NAME-OLDVERSION NAME-NEWVERSION
.SH DESCRIPTION
pkgup is a shell program provided by yalpack (Yet Another Lfs PACKage manager) to upgrade packages made by pkgmake and installed by pkginst. The tarballs for both versions must be present.

pkgup begins by installing the new package with pkginst(1); from here, /var/yalpack/pkgdata/TREES is referenced to remove any unneeded files, symlinks or directories installed by the old version of the package. Because the home directory is the responsibility of the user/administrator, pkgup will never remove anything from /home.

In case of symlink removal or other inconveniences, any install.sh script for the new package will be re-run before checking for information about the new package with pkgcheck(1).

By default, pkgup references and writes to the following directories:

\t /var/yalpack/pkgdata/TREES/[NAME] (a copy of the package tree is written here for reference)

\t /var/yalpack/pkgdata/VER/[NAME] (a file with the package's version number)

\t /var/yalpack/pkgdata/PKG-DEPS/[NAME]/libdeps (any libraries used by installed binaries)

\t /var/yalpack/pkgdata/PKG-BINS/[NAME]/instbins (any installed programs)

\t /var/yalpack/pkgdata/PKG-LIBS/[NAME]/libs (any installed libraries)

The pkgup script can be edited to change any of these default locations to suit user preferences. This is best done before installation and in conjunction with the other yalpack scripts.
.SH OPTIONS
NAME - the name of the package

OLDVERSION - the outgoing package's version number

NEWVERSION - the incoming package's version number
.SH SEE ALSO
pkgmake(1), pkginst(1), pkgcheck(1), pkgremove(1)
.SH BUGS
pkgup is not equipped to handle upgrades with differing package names. In such cases, the recommended workflow is to use pkginst(1) to install the new package, and then run pkgremove(1) to remove the old package.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
