.\" Manpage for /usr/share/yalpack/restore-yalpack
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 8 "10 September 2021" "0.2.0" "restore-yalpack man page"
.SH NAME
.B restore-yalpack
\(em restore the yalpack data directories using a collection of package trees 
.SH SYNOPSIS
.B /usr/share/yalpack/restore-yalpack
(default location)
.SH DESCRIPTION
.B restore-yalpack
is a shell program provided by
.B yalpack
(Yet Another Lfs PACKage manager) for regenerating the
.B yalpack
directory structure and contents under
.I /var/yalpack
using a collection of package trees.
.B pkginst(1)\fR\
,
.B pkgup(1)
and
.B pkgremove(1)
update the following package tree directories as packages are added, upgraded and removed:

.I \t /var/yalpack/pkgdata/TREES
.br
.I \t
(main directory)

.I \t /var/log/yalpack
.br
.I \t
(primary backup)

.I \t /root/.yalpack-backup
.br
.I \t
(secondary backup)

The \(lqbackup\(rq directories are not true backups, but rather parallel directories, in that they are modified together with the main directory and not copied over. This serves to prevent accidental damage from affecting the backup and restoration process. Although they cannot be used by the
.B yalpack
scripts in
.I /usr/bin
and
.I /usr/sbin\fR\
, they are available to restore the
.B yalpack
data directory in case of accidents or other data loss.

.B restore-yalpack
uses the following priority order in determining which collection of package trees to use to regenerate the data directories:

.TQ
.I \t /var/log/yalpack
.TQ
.I \t /root/.yalpack-backup
.TQ
.I \t /var/yalpack/pkgdata/TREES

.P
If none of these locations is a non-empty directory, the script will exit. To specify a directory other than an existing
.I /var/log/yalpack\fR\
, change the value of the following variable in
.I /etc/yalpack.conf\fR\
:

.I \t VARBKUP=/var/log/yalpack

Once a directory has been detected and approved by user input, the following
.B yalpack
directories and their contents will be regenerated based on the collection of package trees:

.I \t /var/yalpack/pkgdata/TREES
.br
.I \t
(via copy; if the
.I TREES
directory exists when the script is run, a copy is retained at
.I /var/yalpack/pkgdata/TREES-OLD\fR\
)

.I \t /var/yalpack/BIN-DEPS
.br
.I \t
Generated by 
.B liblist(1)

.I \t /var/yalpack/pkgdata/PKG-BINS
.br
.I \t
Generated by
.B pkgcheck(1)

.I \t /var/yalpack/pkgdata/PKG-DEPS
.br
.I \t
Generated by
.B pkgcheck(1)

.I \t /var/yalpack/pkgdata/PKG-LIBS
.br
.I \t
Generated by
.B pkgcheck(1)

.I \t /var/yalpack/pkgdata/NEWFILES

.I \t /var/yalpack/pkgdata/SYMTREES

.I \t /var/yalpack/pkgdata/.SYMDESTS

.I \t /var/yalpack/pkgdata/VER

Package tarballs cannot be restored by
.B restore-yalpack\fR\
. However, all
.B yalpack
scripts should be able to operate normally if
.B restore-yalpack
uses a good backup to regenerate the directories above.
.B restore-yalpack
needs
.B liblist(1)
and
.B pkgcheck(1)
in the path, and should be run as root.
.SH SEE ALSO
.B pkginst(1)\fR\
,
.B pkgup(1)\fR\
,
.B pkgremove(1)\fR\
,
.B liblist(1)\fR\
,
.B pkgcheck(1)
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson
.MT kvngncrlsn@gmail.com
.ME
