.\" Manpage for yalfind
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "10 September 2021" "0.2.0" "yalfind man page"
.SH NAME
.B yalfind
\(em search for which package provided matching files/symlinks/directories 
.SH SYNOPSIS
.B yalfind [-xf|--exact --showfile] SEARCHTERM1 ...
.SH DESCRIPTION
.B yalfind
is a shell program provided by
.B yalpack
(Yet Another Lfs PACKage manager) for checking which yalpack package or packages provided files, symlinks or directories matching a search term.
.B yalfind
searches the
.I TREE
and
.I SYMTREE
files for all installed packages, located by default in
.I /var/yalpack/pkgdata/TREES\fR\
\&.

.B --exact (-x)
can be passed as a parameter to search for exact matches with the user-provided path. If
.B --exact
is used,
.B yalfind
will display .new files as matches, as in this example:

.B \t yalfind -xf /etc/pulse/client.conf

.B \t 
/etc/pulse/client.conf:

.B \t 
pulseaudio:/etc/pulse/client.conf.new

For files installed under a path with a symlink, either file path should generate results.
.SH OPTIONS
.TQ
.B SEARCHTERM
.br
A search term for the desired file, directory or link path.

.TQ
.B -x|--exact
.br
Show results for an exact file path.

.TQ
.B -f|--showfile
.br
Show the file name(s) along with the package(s).

.TQ
.B -h|--help
.br
Display the help menu.
.SH BUGS
No known bugs.
.SH AUTHOR
K. Eugene Carlson
.MT kvngncrlsn@gmail.com
.ME
