#!/bin/sh
#
# liblist: for library check support on LFS systems
#
# Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Checking dynamic libraries called in by all binaries. Must be run as root or there will be no information about /sbin and /usr/sbin.

HEAD=/var/yalpack
BINDEPS=$HEAD/BIN-DEPS
mkdir -p "$BINDEPS"

# The function to check libraries for an individual binary
populate() {
BIN="$(basename "$1")"
# An empty variable name here would be really bad
[ -z "$BIN" ] && return
# Not interested in library files here
[ -n "$(echo "$BIN" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ] && return
BINDIR="$BINDEPS/$BIN"
mkdir -p "$BINDIR"
echo "$BIN" checked "$(date)" > "$BINDIR/$BIN.libinfo"
ldd "$1" >> "$BINDIR/$BIN.libinfo"
# Don't need empty entries
[ "$(wc -l "$BINDIR/$BIN.libinfo")" = "1 $BINDIR/$BIN.libinfo" ] && rm -rf "$BINDIR"
}

# A new dynamic library usage data collection
new() {
[ -d "$BINDEPS".old ]; rm -rf "$BINDEPS.old"
[ -d "$BINDEPS" ] && mv "$BINDEPS" "$BINDEPS.old"
mkdir -p "$BINDEPS"
for d in /bin /usr /sbin /opt; do
	# Only look in if directory exists, is not a symlink and is non-empty
	if [ -d "$d" ] && [ ! -h "$d" ] && [ -n "$(ls -A "$d")" ]; then
		echo Checking $d
		find $d/* -executable -type f | while read -r file; do populate "$file"; done
	fi
done
}

if [ -z "$1" ]; then
	new
else
	for arg in "$@"; do
		case "$arg" in
			-h|--help)
			echo
			echo $(tput smul)liblist$(tput rmul): Generate dynamic library information, separated by binary and stored in
			echo /var/yalpack/BINDEPS
			echo
			echo Syntax: liblist \(options\) \(PATH1 PATH2 ... \)
			echo
			echo A PATH input is the full path to a binary. If one or more PATH variables is used,
			echo liblist will add information for these binaries only. Starting with the \-n flag
			echo will generate a fresh collection once, and then update thereafter.
			echo
			echo Flags:
			echo "  -n | --new : Make a new collection at /var/yalpack/bindeps (default behavior)"
			echo "  -h | --help : Display this help menu"
			echo
			exit
			;;
			-n|--new)
			new
			;;
			*)
			[ -n "$arg" ] && populate "$arg"
		esac
	done
fi
