#!/bin/sh
#
# pkginst: installing a package on LFS systems
#
# Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Installing a package from a source tarball

# If called by another script, use the passed-in variables to save time.
if [ "${YALCONFIG:-no}" = no ]; then

unset HEAD
unset VARBKUP
unset ROOTHOME
unset TMP
unset SBINDIR

CHOME=/etc/yalpack.conf
HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"

if [ ! -f "$CHOME" ]; then
        echo
        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
        echo The document can be found in its originally-installed state at
        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
        echo
        echo Exiting now
        echo
        exit 1
fi

COUNT1=0
for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
        COUNT1=$((COUNT1 + 1))
        COUNT2=0
        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
                COUNT2=$((COUNT2 + 1))
                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
                        echo
                        exit 1
                fi
        done
done
fi

main (){
STAGING="$HEAD"/packages
PKGDIR="$STAGING"/"$PACK"
PKGDATA="$HEAD"/pkgdata
PKGDEST="$PKGDIR"/dest
PKGTREES="$PKGDATA"/TREES
SYMTREES="$PKGDATA"/SYMTREES
SYMDESTS="$PKGDATA"/.SYMDESTS
PKGVER="$PKGDATA"/VER
NEWFILES="$PKGDATA"/NEWFILES
BUILDDEST="$TMP"/dest/"$PACK"

# Backups

# Placing yalpack data directories in locations not owned by root is not
#i recommended.
ROOTBKUP="$ROOTHOME"/.yalpack-backup

echo
echo '	'Installing package $(tput smul)"$PACK"$(tput rmul).
echo
set -e
mkdir -p "$STAGING"
mkdir -p "$PKGDATA" "$PKGTREES" "$PKGVER" "$NEWFILES"
cd "$STAGING"
tar -xf "$PACK".tar.xz
NAME=$(cat "$PKGDIR"/NAME)

# Exit code not necessary because pkgup already checks for TREE.
[ ! -d "$PKGDEST" ] && echo '	'$(tput smul)Warning! "$PKGDEST"$(tput rmul) was not found. Exiting. && exit

cd "$PKGDEST"
# Patrick Volkerding says non-755 root is dangerous, so it can't hurt (for
# safety when extracting the package to root).
chmod 755 "$PKGDEST"
# If --root-own was passed in, change ownership to root:root. Ownership is
# preserved at the actual install stage.
[ "$3" = "CHOWN" ] && chown -R root:root "$PKGDEST"

# Non-directories, non-symlinks and non-binaries in etc and home will be .new;
# check for identical/unique. Doing nothing means .new installed. (Any other
# file named .new manually will be checked similarly.)
rm -f "$NEWFILES"/"$NAME"
find "$PKGDEST"/ -type f | while read -r f;	
do
	h="${f##$PKGDEST/}"
	i="${h%.new}"
	# Proceed if the file is .new
	if [ "$i" != "$h" ]; then
		# The non-.new version will be called this, if needed
		j="${f%.new}"
		# If file exists, check for differences
		if [ -f "/$i" ]; then
			md5f=$(md5sum "$f" | cut -d' ' -f-1)
			md5i=$(md5sum "/$i" | cut -d' ' -f-1)
			# If not different, new file is not needed
			if [ "$md5f" = "$md5i" ]; then
				rm -f "$f"
			else
				# If .new file will be installed, log it and
				# show the user afterwards.
				[ ! -f "$NEWFILES"/"$NAME" ] && echo "$PACK" >> "$NEWFILES"/"$NAME"
				echo "/$h" >> "$NEWFILES"/"$NAME"
				# Change the .new file ownership and mode to 
				# match the existing file (mostly relevant for 
				# rc files)
				chown "$(stat -c "%U:%G" "/$i")" "$f"
				chmod "$(stat -c "%a" "/$i")" "$f"
			fi
		# If file DNE, don't call the new one .new
		else
			mv "$f" "$j"
		fi
	fi
done
echo '	'Done evaluating the $(tput smul).new$(tput rmul) files, if any.
echo

# Preparing and reporting on symlinks; absolute symlinks can have been pointed 
# at either the ultimate destination or a file/directory in the build directory.
# Symlinks that required repair will be reported.
while read -r f;
do
	if [ -h "$PKGDEST"/"$f" ]; then
	i="${f#/}"
	j=$(readlink "$i")
	# If the symlink is absolute; BUILDDEST needed to test it out. (Just the
	# string; the directory itself doesn't need to exist for pkginst to
	# work.)
	if [ -n "$(echo "$j" | grep -m 1 "$BUILDDEST")" ]; then
		# Pointing at BUILDDEST from time of building.
		k="${j##$BUILDDEST}"
		echo /"$i" "to" "$k" >> "$PKGDIR"/SYMLINKS
		ln -sfn "$k" "$i"
		echo
	fi
	fi
done < "$PKGDIR"/TREE

[ -f "$PKGDIR/SYMLINKS" ] && echo '	'Symlink checks and repairs complete. && echo

# Now that changes have been made to dest, make a new tarball for extraction...
echo '	'$(tput smul)Repackaging$(tput rmul)...
tar -czf "$STAGING"/INPACKAGE.tar.xz ./*
# And extract over root. (dereferencing for links; don't change directory mode or
# ownership)
cd /
echo '	'$(tput smul)Extracting now$(tput rmul)...
tar --dereference --hard-dereference -xf "$STAGING"/INPACKAGE.tar.xz --no-overwrite-dir
cd "$PKGDIR"
echo '	'Done.
echo

# Running ldconfig in case of new libraries; in case of an upgrade, it should be
# run after removal.
if [ "${UPGRADE:-no}" != yes ]; then
	ldconfig
	echo '	'Done running $(tput smul)ldconfig$(tput rmul).
	echo
fi

# Populate the TREE entry for future updating
cat "$PKGDIR"/TREE > "$PKGTREES"/"$NAME"
# Saving to the backup locations as well, if they exist. The install script for
# yalpack will make and populate them otherwise.
[ -d "$VARBKUP" ] && cat "$PKGDIR"/TREE > "$VARBKUP"/"$NAME"
[ -d "$ROOTBKUP" ] && cat "$PKGDIR"/TREE > "$ROOTBKUP"/"$NAME"

# Add version information to /var/yalpack/pkgdata
cat "$PKGDIR"/VER > "$PKGVER"/"$NAME"

# Make the SYMTREES document, if needed. If the directory does not yet exist,
# the install script for yalpack will make and populate it.
unset SYMTREEFLAG
if [ -d "$SYMTREES" ]; then
	rm -f "$PKGDATA"/SYMTEMP
	rm -f "$PKGDATA"/SYMTEMP2
	echo '	'Checking for installations under paths with symlinks.
	while read -r line; do
		[ -d "$line" ] && [ -h "$line" ] && echo "$line" >> "$PKGDATA"/SYMTEMP	    
	done < "$PKGTREES"/"$NAME"

	[ -f "$PKGDATA"/SYMTEMP ] && while read -r dir; do
		grep ^"$dir" "$PKGTREES"/"$NAME" >> "$PKGDATA"/SYMTEMP2
	done < "$PKGDATA"/SYMTEMP
	
	[ -f "$PKGDATA"/SYMTEMP2 ] && while read -r sym; do
		unset link
		unset linkold
		unset linkOK
		unset linkoldOK

		symold="${sym%.new}"

		link="$(readlink -e "$sym")" || true
		linkold="$(readlink -e "$symold")" || true

		[ -n "$(echo "$link")" ] && linkOK=yes
		[ -n "$(echo "$linkold")" ] && linkoldOK=yes

		unset writeOK
		unset writeoldOK
		unset SYMTREEFLAG

		[ "$linkOK" = yes ] && [ -z "$(grep -m 1 -x "$link" "$PKGTREES"/"$NAME")" ] && writeOK=yes
		[ "$linkoldOK" = yes ] && [ -z "$(grep -m 1 -x "$linkold" "$PKGTREES"/"$NAME")" ] && writeoldOK=yes

		if [ "$writeOK" = yes ] && [ "$writeoldOK" = yes ]; then
			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$linkold" >> "$SYMDESTS"/"$NAME"
		elif [ "$writeoldOK" = yes ] && [ -z "$link" ]; then
			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$linkold" >> "$SYMDESTS"/"$NAME"
		elif [ "$writeOK" = yes ] && [ -z "$linkold" ]; then
			echo "$sym" to "$link" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$link" >> "$SYMDESTS"/"$NAME"
		fi
	done < "$PKGDATA"/SYMTEMP2

	if [ "$SYMTREEFLAG" = "WRITE" ]; then
		echo
		cat "$SYMTREES"/"$NAME"
		echo
	fi
	echo '	'Done.
	echo
	rm -f "$PKGDATA"/SYMTEMP
	rm -f "$PKGDATA"/SYMTEMP2
fi

# Run the install script, if any
if [ -x "$PKGDIR/install.sh" ]; then 
	echo '	'Now running $(tput smul)install.sh$(tput rmul).
	echo
	"$PKGDIR"/install.sh
	echo
fi

# For the installer's edification and to update library use info.
# pkgup handles pkgcheck for upgrades.
if [ "${UPGRADE:-no}" != yes ]; then
	YALCONFIG=yes \
	HEAD="$HEAD" \
	VARBKUP="$VARBKUP" \
	ROOTHOME="$ROOTHOME" \
	TMP="$TMP" \
	SBINDIR="$SBINDIR" \
	CHECK=no "$SBINDIR"/pkgcheck "$NAME"
fi

# Inform about any repaired symlinks
if [ -f "$PKGDIR/SYMLINKS" ]; then 
	echo '	'The following $(tput smul)absolute symlinks$(tput rmul) were repaired before installation:
	echo
	cat "$PKGDIR"/SYMLINKS
	echo
fi

# Inform about any .new files
if [ -f "$NEWFILES/$NAME" ]; then
	echo '	'The following $(tput smul).new$(tput rmul) files should be examined:
	echo
	cat "$NEWFILES"/"$NAME"
	echo
	echo '	'The list will be stored at $(tput smul)"$NEWFILES"/"$NAME"$(tput rmul) for reference.
	echo '	'Run $(tput smul)/usr/share/yalpack/newfiles$(tput rmul) at any time to manage $(tput smul).new$(tput rmul) files.
	echo
fi

if [ "$SYMTREEFLAG" = "WRITE" ]; then
	echo '	'$(tput smul)One or more installations under a symlink path have been detected.$(tput rmul)
	# This may happen from time to time with merged-usr. Without merged-usr, it 
	# probably shouldn't.
	if [ ! -h "/bin" ]; then
		echo '	'This may be a sign that the package was built incorrectly. See 
		echo '	'$(tput smul)"$SYMTREES"/"$NAME"$(tput rmul) for a list.
	else
		echo '	'See $(tput smul)"$SYMTREES"/"$NAME"$(tput rmul) for a list.
	fi
	echo
fi

# Clean up afterwards (INPACKAGE is never retained)
cd "$STAGING"
rm -f "$STAGING"/INPACKAGE.tar.xz
rm -rf "${PKGDIR:?}"
if [ "$2" != "KEEP" ]; then
	rm -f $STAGING/"$PACK".tar.xz
	echo '	'The package tarball has been removed. See $(tput smul)$PKGTREES/"$NAME"$(tput rmul)
	echo '	'for a list of installed files, symlinks and directories.
	echo
fi

echo '	'Installation of $(tput smul)"$PACK"$(tput rmul) complete.
echo
}
unset KEEP
unset PACK
unset CHANGE
unset CHOWN
for arg in "$@"; do
	case "$arg" in
		-h|--help)
		echo
		echo $(tput smul)pkginst$(tput rmul): Install a yalpack package from a package tarball in /var/yalpack/packages
		echo
		echo Syntax: pkginst \(options\) NAME1-VER1 NAME2-VER2 ...
		echo 
		echo The package version should not be included if the NAME file contains the entire name-
		echo version string.
		echo
		echo Flags:
		echo "  -k | --keep : Retain the package tarball in /var/yalpack/packages after installation"
		echo "  -r | --root-own : Change the ownership of the contents of the package to" 
		echo "  root:root before installation. Useful for packages that were built and are owned by"
		echo "  a non-privileged user."
		echo "  -h | --help : Display this help menu"
		echo
		exit
		;;
		-k|--keep)
		KEEP=KEEP
		;;
		-r|--root-own)
		CHOWN=CHOWN
		;;
		-kr|-rk)
		KEEP=KEEP
		CHOWN=CHOWN
		;;
		*)
		PACK="$arg"
		main "$PACK" "$KEEP" "$CHOWN"
	esac
done
