#!/bin/sh
#
# pkginst: installing a package on LFS systems
#
# Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Installing a package from a source tarball

# If called by another script, use the passed-in variables to save time.
if [ "${YALCONFIG:-no}" = no ]; then

unset HEAD
unset VARBKUP
unset ROOTHOME
unset TMP
unset SBINDIR

CHOME=/etc/yalpack.conf
HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"

if [ ! -f "$CHOME" ]; then
        echo
        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
        echo The document can be found in its default state at
        echo $(tput smul)/usr/share/doc/yalpack-0.2.0/yalpack.conf.backup.$(tput rmul)
        echo
        echo Exiting now
        echo
        exit 1
fi

COUNT1=0
for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
        COUNT1=$((COUNT1 + 1))
        COUNT2=0
        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
                COUNT2=$((COUNT2 + 1))
                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
                        echo
                        exit 1
                fi
        done
done
fi

main (){
STAGING="$HEAD"/packages
PKGDIR="$STAGING"/"$PACK"
PKGDATA="$HEAD"/pkgdata
PKGDEST="$PKGDIR"/dest
PKGTREES="$PKGDATA"/TREES
SYMTREES="$PKGDATA"/SYMTREES
SYMDESTS="$PKGDATA"/.SYMDESTS
PKGVER="$PKGDATA"/VER
NEWFILES="$PKGDATA"/NEWFILES
TEMPDOC="$PKGDATA"/TEMPDOC
TEMPDIR="$PKGDATA"/TEMPDIR
EXCLUDE="$PKGDATA"/EXCLUDE

# Backups

# Placing yalpack data directories in locations not owned by root is not
# recommended.
ROOTBKUP="$ROOTHOME"/.yalpack-backup

echo
echo '	'Installing package $(tput smul)"$PACK"$(tput rmul).
echo
set -e
mkdir -p "$STAGING"
mkdir -p "$PKGDATA" "$PKGTREES" "$PKGVER" "$NEWFILES"
cd "$STAGING"
# Sanity checks
[ -z "$PACK" ] && echo && echo '	'$(tput smul)pkginst$(tput rmul) needs a package as a parameter. && echo && exit 1
[ -z "$(tar -tf "$PACK".tar.xz | grep -x -m 1 "$PACK"/dest/)" ] && echo '	'$(tput smul)Warning! The "dest" directory$(tput rmul) was not found. Exiting. && echo && exit 1
tar -xf "$PACK".tar.xz --exclude="$PACK"/dest
NAME=$(cat "$PACK"/NAME)
[ ! -f "$PACK"/NAME ] && echo '	'$(tput smul)Warning!$(tput rmul) This package has no $(tput smul)NAME$(tput rmul) file. Exiting now. && rm -rf "$PACK" && echo && exit 1
[ ! -f "$PACK"/TREE ] && echo '	'$(tput smul)Warning!$(tput rmul) This package has no $(tput smul)TREE$(tput rmul) file. Exiting now. && rm -rf "$PACK" && echo && exit 1

# install.sh (if any) stays for now to be run later.
mv "$PACK"/TREE "$PKGTREES"/"$NAME"
mv "$PACK"/VER "$PKGVER"/"$NAME"
[ -x "$PACK"/install.sh ] && mv "$PACK"/install.sh "$STAGING"
rm -rf "$PACK"

# If --root-own was passed in, change ownership to root:root. Ownership is
# preserved at the actual install stage.
if [ "$3" = "CHOWN" ] && [ -n "$(tar -tvf "$PACK".tar.xz | grep -v " root/root ")" ]; then
	# If a non-root-owned item is found, extracting and repacking can't be
	# helped.
	tar -xf "$PACK".tar.xz
       	chown -R root:root "$PKGDEST"
	rm -f "$PACK".tar.xz
	tar -caf "$PACK".tar.xz "$PKGDIR"
fi
rm -rf "$TEMPDIR"
rm -f "$EXCLUDE"
mkdir -p "$TEMPDIR"
cd "$TEMPDIR"
# Non-directories, non-symlinks and non-binaries in etc and home will be .new;
# check for identical/unique. Doing nothing means .new installed. (Any other
# file named .new manually will be checked similarly.)
rm -f "$NEWFILES"/"$NAME" "$TEMPDOC"
NEWS="$(grep ".new$" "$PKGTREES"/"$NAME")" || true
[ -n "$NEWS" ] && echo "$NEWS" > "$TEMPDOC"

# This flag will be used if a secondary package tarball is needed for .new file
# changes.
unset SUPPLEMENTARY

[ -f "$TEMPDOC" ] && while read -r f; do
	y="$PACK"/dest"$f"
	tar -xf "$STAGING"/"$PACK".tar.xz --strip-components 2 "$y"
	g="${f#/}"
	h="${f%.new}"
	# If file exists, check for differences
	if [ -f "$h" ]; then
		md5g=$(md5sum "$g" | cut -d' ' -f-1)
		md5h=$(md5sum "$h" | cut -d' ' -f-1)
		# If not different, new file is not needed
		if [ "$md5g" = "$md5h" ]; then
			# Keeping TEMPDIR's directory tree tidy.
			i="$(dirname "$g")"
			rm -f "$g"
			rmdir --parents --ignore-fail-on-non-empty "$i"
			echo "$y" >> "$EXCLUDE"
		else
			# If .new file will be installed, log it and
			# show the user afterwards.
			[ ! -f "$NEWFILES"/"$NAME" ] && echo "$PACK" >> "$NEWFILES"/"$NAME"
			echo "$f" >> "$NEWFILES"/"$NAME"
			# Change the .new file ownership and mode to 
			# match the existing file (mostly relevant for 
			# rc files)
			chown "$(stat -c "%U:%G" "$h")" "$g"
			chmod "$(stat -c "%a" "$h")" "$g"
			SUPPLEMENTARY=yes
		fi
	# If file DNE, don't call the new one .new
	else
		j="${g%.new}"
		mv "$g" "$j"
		echo "$y" >> "$EXCLUDE"
		SUPPLEMENTARY=yes
	fi
done < "$TEMPDOC"

# If any .new files will be installed to the system (under any name), a second
# package tarball will be required. Making it now.
[ "$SUPPLEMENTARY" = "yes" ] && tar -caf "$STAGING"/SUPPLEMENTARY.tar.xz ./*

if [ -f "$TEMPDOC" ]; then
	echo '	'Done evaluating the $(tput smul).new$(tput rmul) files.
	echo
fi

rm -f "$TEMPDOC"

# Starting with 0.2.0, symlink repair has been handled by pkgmake.

# Extract over root. (dereferencing for links; don't change directory mode or
# ownership)
cd /
echo '	'$(tput smul)Extracting now$(tput rmul)...
touch "$EXCLUDE"
tar --dereference --hard-dereference -xf "$STAGING"/"$PACK".tar.xz --wildcards --strip-components 2 "$PACK"/dest/* --no-overwrite-dir --exclude-from="$EXCLUDE"
# Extract the supplementary tarball as well, if present.
[ -f "$STAGING"/SUPPLEMENTARY.tar.xz ] && tar --dereference --hard-dereference -xf "$STAGING"/SUPPLEMENTARY.tar.xz --no-overwrite-dir
cd "$STAGING"
echo '	'Done.
echo

# Running ldconfig in case of new libraries; in case of an upgrade, it should be
# run after removal.
if [ "${UPGRADE:-no}" != yes ]; then
	ldconfig
	echo '	'Done running $(tput smul)ldconfig$(tput rmul).
	echo
fi

# Saving to the backup locations as well, if they exist. The install script for
# yalpack will make and populate them otherwise.
[ -d "$VARBKUP" ] && cat "$PKGTREES"/"$NAME" > "$VARBKUP"/"$NAME"
[ -d "$ROOTBKUP" ] && cat "$PKGTREES"/"$NAME" > "$ROOTBKUP"/"$NAME"

# Make the SYMTREES document, if needed. If the directory does not yet exist,
# the install script for yalpack will make and populate it.
unset SYMTREEFLAG
if [ -d "$SYMTREES" ]; then
	rm -f "$PKGDATA"/SYMTEMP
	rm -f "$PKGDATA"/SYMTEMP2
	while read -r line; do
		[ -d "$line" ] && [ -h "$line" ] && echo "$line" >> "$PKGDATA"/SYMTEMP	    
	done < "$PKGTREES"/"$NAME"

	[ -f "$PKGDATA"/SYMTEMP ] && while read -r dir; do
		grep ^"$dir" "$PKGTREES"/"$NAME" >> "$PKGDATA"/SYMTEMP2
	done < "$PKGDATA"/SYMTEMP
	
	[ -f "$PKGDATA"/SYMTEMP2 ] && while read -r sym; do
		unset link
		unset linkold
		unset linkOK
		unset linkoldOK

		symold="${sym%.new}"

		link="$(readlink -e "$sym")" || true
		linkold="$(readlink -e "$symold")" || true

		[ -n "$(echo "$link")" ] && linkOK=yes
		[ -n "$(echo "$linkold")" ] && linkoldOK=yes

		unset writeOK
		unset writeoldOK
		unset SYMTREEFLAG

		[ "$linkOK" = yes ] && [ -z "$(grep -m 1 -x "$link" "$PKGTREES"/"$NAME")" ] && writeOK=yes
		[ "$linkoldOK" = yes ] && [ -z "$(grep -m 1 -x "$linkold" "$PKGTREES"/"$NAME")" ] && writeoldOK=yes

		if [ "$writeOK" = yes ] && [ "$writeoldOK" = yes ]; then
			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$linkold" >> "$SYMDESTS"/"$NAME"
		elif [ "$writeoldOK" = yes ] && [ -z "$link" ]; then
			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$linkold" >> "$SYMDESTS"/"$NAME"
		elif [ "$writeOK" = yes ] && [ -z "$linkold" ]; then
			echo "$sym" to "$link" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
			echo "$link" >> "$SYMDESTS"/"$NAME"
		fi
	done < "$PKGDATA"/SYMTEMP2

	if [ "$SYMTREEFLAG" = "WRITE" ]; then
		echo
		cat "$SYMTREES"/"$NAME"
		echo
	fi
	rm -f "$PKGDATA"/SYMTEMP
	rm -f "$PKGDATA"/SYMTEMP2
fi

# Run the install script, if any
if [ -x "$STAGING/install.sh" ]; then 
	echo '	'Now running $(tput smul)install.sh$(tput rmul).
	echo
	"$STAGING"/install.sh
	echo
fi

# For the installer's edification and to update library use info.
# pkgup handles pkgcheck for upgrades.
if [ "${UPGRADE:-no}" != yes ]; then
	YALCONFIG=yes \
	HEAD="$HEAD" \
	VARBKUP="$VARBKUP" \
	ROOTHOME="$ROOTHOME" \
	TMP="$TMP" \
	SBINDIR="$SBINDIR" \
	CHECK=no "$SBINDIR"/pkgcheck "$NAME"
fi

# Inform about any .new files
if [ -f "$NEWFILES/$NAME" ]; then
	echo '	'The following $(tput smul).new$(tput rmul) files should be examined:
	echo
	cat "$NEWFILES"/"$NAME"
	echo
	echo '	'The list will be stored at $(tput smul)"$NEWFILES"/"$NAME"$(tput rmul) for reference.
	echo '	'Run $(tput smul)/usr/share/yalpack/newfiles$(tput rmul) at any time to manage $(tput smul).new$(tput rmul) files.
	echo
fi

if [ "$SYMTREEFLAG" = "WRITE" ]; then
	echo '	'$(tput smul)One or more installations under a symlink path have been detected.$(tput rmul)
	# This may happen from time to time with merged-usr. Without merged-usr, it 
	# probably shouldn't.
	if [ ! -h "/bin" ]; then
		echo '	'This may be a sign that the package was built incorrectly. See 
		echo '	'$(tput smul)"$SYMTREES"/"$NAME"$(tput rmul) for a list.
	else
		echo '	'See $(tput smul)"$SYMTREES"/"$NAME"$(tput rmul) for a list.
	fi
	echo
fi

# Clean up afterwards (SUPPLEMENTARY.tar.xz is never retained)
cd "$PKGDATA"
rm -f "$STAGING"/SUPPLEMENTARY.tar.xz "$TEMPDOC" "$EXCLUDE"
rm -rf "$TEMPDIR"
cd "$STAGING"
rm -f install.sh
if [ "$2" != "KEEP" ]; then
	rm -f $STAGING/"$PACK".tar.xz
	echo '	'The package tarball has been removed. See $(tput smul)$PKGTREES/"$NAME"$(tput rmul)
	echo '	'for a list of installed files, symlinks and directories.
	echo
fi

echo '	'Installation of $(tput smul)"$PACK"$(tput rmul) complete.
echo
}
unset KEEP
unset PACK
unset CHANGE
unset CHOWN
for arg in "$@"; do
	case "$arg" in
		-h|--help)
		echo
		echo $(tput smul)pkginst$(tput rmul): Install a yalpack package from a package tarball in /var/yalpack/packages
		echo
		echo Syntax: pkginst \(options\) NAME1-VER1 NAME2-VER2 ...
		echo 
		echo The package version should not be included if the NAME file contains the entire name-
		echo version string.
		echo
		echo Flags:
		echo "  -k | --keep : Retain the package tarball in /var/yalpack/packages after installation"
		echo "  -r | --root-own : Change the ownership of the contents of the package to" 
		echo "  root:root before installation. Useful for packages that were built and are owned by"
		echo "  a non-privileged user."
		echo "  -h | --help : Display this help menu"
		echo
		exit
		;;
		-k|--keep)
		KEEP=KEEP
		;;
		-r|--root-own)
		CHOWN=CHOWN
		;;
		-kr|-rk)
		KEEP=KEEP
		CHOWN=CHOWN
		;;
		*)
		PACK="$arg"
		main "$PACK" "$KEEP" "$CHOWN"
	esac
done
