#!/bin/sh
#
# pkgup: used to upgrade packages (made by pkgmake and installed by pkginst) on LFS systems
#
# Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Used to upgrade packages to a new version. HANDLE WITH CARE.

STAGING=/var/yalpack/packages
NEWDIR=$STAGING/"$2"
PKGTREES=/var/yalpack/pkgdata/TREES

echo
echo It is advised to run pkgcheck on the old package first.
echo
echo Upgrade of "$1" to "$2" has been requested. To proceed, press \"y\". IF YOU HAVE ANY DOUBTS, TERMINATE THE PROCESS NOW.
read -r INPUT
echo
[ "$INPUT" != "y" ] && exit

set -e
cd $STAGING
[ ! -d "$NEWDIR" ] && tar -xf $STAGING/"$2".tar.xz
# Sanity check
[ ! -f "$NEWDIR/TREE" ] && echo Warning! The TREE file for "$2" could not be found. Try running pkgmake again. Exiting now. && exit

# To save time, don't want to delete files from the old package unless they're unneeded; those shared with the new package will be overwritten in any case.
cat "$NEWDIR"/TREE > "$PKGTREES/YALPACK-INCOMING"
rm -r "$NEWDIR"

# pkgremove and pkginst can use their own error handling
set +e
UPGRADE=yes /sbin/pkgremove "$1"
/sbin/pkginst "$2"
set -e

# Cleaning up
cd $STAGING
rm -f "$PKGTREES/YALPACK-INCOMING"

echo The upgrade from "$1" to "$2" is complete.
echo
